travis:
  secure:
    BINSTAR_TOKEN: ITfOKnwFQdQrxbmNIyj+Z/pFMpC38E+qJtjacY7lCmarPuuVKqbI5JCPmBo2/zpfysK2TcFO8yEI2JUI8k92vvIaKuc5A5lOTcV/B9vW//re/rXhKNPW0qvhejSIbtIlM2auqyJWM0Fr9+TlZ3nuOY9ge/Kil+id3aZodVFiCrxWArFyXPnAIe7vOrtCCbV/aaMLSvB2PbtNgEIaILQ8i3OrgK56xZ9EPvdRlW3pfWk2IX7p5naFM/jLgnzMR7tcemUEMAU02gUo86vm+xrhlZIUWhvX1E/gbMAk/lr4lZUiFsLODEP11Oai6WryxwnVcVbggC6IpTstKPChBD8mfuIWiNi7OainKZ3vGDJibhKMuMKSb9a6Y164iZudCIEMaLI13S9/oirjOe/3IQBw9O3xx4oqHs81vj3oiqzgUCZqPGEUG6bTiXF1ozBJxM2N//gFjxUW2DbYe+p7N3OfI63+wEy5D/7SCCOmrnTdMwu1HPRpvsw0qsfcBYAuk/0XmafOUOnvnk8MBRrBLpVBQ+cpG/kVWGvgJZNatLMalZXkA1JnNo4ByRmwb7y937vQWj0y+Rl1LZ5ZavTyaAM0vsLMh9zGKOxmDrRJbohcLrWpEN98nHMN6pGwNUsQIwUd4B1TQGG96AxP0odF5Gb6ku2cRxBVLNBCjPkS/QVv8RY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
